spring:
  application:
    name: "product-service"
  datasource:
    url: jdbc:h2:file:./data/mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      show-sql: true
  logging:
    level:
      root: DEBUG
      org.springframework: DEBUG
  sql:
    init:
      mode: always
  artemis.users: artemis
  artemis.passwords: simetraehcapa

izanis:
  factory:
    inventoryUser: admin
    inventoryPassword: password
    productInventoryServiceHost: address

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 100
        minimumNumberOfCalls: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      inventoryService:
        baseConfig: default